parameters:
    # form types
    core.form.type.article.class: CoreBundle\Form\ArticleType
    core.form.type.category.class: CoreBundle\Form\CategoryType
    core.form.type.document.class: CoreBundle\Form\DocumentType
    core.form.type.event.class: CoreBundle\Form\EventType
    core.form.type.hive.class: CoreBundle\Form\HiveType
    core.form.type.user.class: CoreBundle\Form\UserType
    core.form.type.vote.class: CoreBundle\Form\VoteType

    # form handlers
    core.form.handler.abstract.class: CoreBundle\Form\Handler\AbstractFormHandler
    core.form.handler.article.class: CoreBundle\Form\Handler\ArticleHandler
    core.form.handler.category.class: CoreBundle\Form\Handler\CategoryHandler
    core.form.handler.document.class: CoreBundle\Form\Handler\DocumentHandler
    core.form.handler.event.class: CoreBundle\Form\Handler\EventHandler
    core.form.handler.hive.class: CoreBundle\Form\Handler\HiveHandler
    core.form.handler.user.class: CoreBundle\Form\Handler\UserHandler
    core.form.handler.vote.class: CoreBundle\Form\Handler\VoteHandler

    # entity classes
    core.entity.article.class: CoreBundle:Article
    core.entity.category.class: CoreBundle:Category
    core.entity.document.class: CoreBundle:Document
    core.entity.event.class: CoreBundle:Event
    core.entity.hive.class: CoreBundle:Hive
    core.entity.user.class: CoreBundle:User
    core.entity.vote.class: CoreBundle:Vote

    # repository classes
    core.repository.abstract.class: CoreBundle\Entity\Repository\AbstractRepository
    core.repository.article.class: CoreBundle\Entity\Repository\ArticleRepository
    core.repository.category.class: CoreBundle\Entity\Repository\CategoryRepository
    core.repository.document.class: CoreBundle\Entity\Repository\DocumentRepository
    core.repository.event.class: CoreBundle\Entity\Repository\EventRepository
    core.repository.hive.class: CoreBundle\Entity\Repository\HiveRepository
    core.repository.user.class: CoreBundle\Entity\Repository\UserRepository
    core.repository.vote.class: CoreBundle\Entity\Repository\VoteRepository

services:
    # repository as services
    core.repository.abstract:
        class: %core.repository.abstract.class%
        abstract: true
        factory: ["@doctrine.orm.default_entity_manager", "getRepository"]
    core.repository.article:
        class: %core.repository.article.class%
        parent: core.repository.abstract
        arguments:
            - %core.entity.article.class%
    core.repository.category:
        class: %core.repository.category.class%
        parent: core.repository.abstract
        arguments:
            - %core.entity.category.class%
    core.repository.document:
        class: %core.repository.document.class%
        parent: core.repository.abstract
        arguments:
            - %core.entity.document.class%
    core.repository.event:
        class: %core.repository.event.class%
        parent: core.repository.abstract
        arguments:
            - %core.entity.event.class%
    core.repository.hive:
        class: %core.repository.hive.class%
        parent: core.repository.abstract
        arguments:
            - %core.entity.hive.class%
    core.repository.user:
        class: %core.repository.user.class%
        parent: core.repository.abstract
        arguments:
            - %core.entity.user.class%
    core.repository.vote:
        class: %core.repository.vote.class%
        parent: core.repository.abstract
        arguments:
            - %core.entity.vote.class%

    # form handler as services
    core.form.handler.abstract:
        class: %core.form.handler.abstract.class%
        abstract: true
        arguments: [ "@doctrine.orm.default_entity_manager", "@form.factory", "@service_container" ]
    core.form.handler.article:
        class: %core.form.handler.article.class%
        parent: core.form.handler.abstract
        calls:
            - [ setFormType, [%core.form.type.article.class%] ]
    core.form.handler.category:
        class: %core.form.handler.category.class%
        parent: core.form.handler.abstract
        calls:
            - [ setFormType, [%core.form.type.category.class%] ]
    core.form.handler.document:
        class: %core.form.handler.document.class%
        parent: core.form.handler.abstract
        calls:
            - [ setFormType, [%core.form.type.document.class%] ]
    core.form.handler.event:
        class: %core.form.handler.event.class%
        parent: core.form.handler.abstract
        calls:
            - [ setFormType, [%core.form.type.event.class%] ]
    core.form.handler.hive:
        class: %core.form.handler.hive.class%
        parent: core.form.handler.abstract
        calls:
            - [ setFormType, [%core.form.type.hive.class%] ]
    core.form.handler.user:
        class: %core.form.handler.user.class%
        parent: core.form.handler.abstract
        calls:
            - [ setFormType, [%core.form.type.user.class%] ]
    core.form.handler.vote:
        class: %core.form.handler.vote.class%
        parent: core.form.handler.abstract
        calls:
            - [ setFormType, [%core.form.type.vote.class%] ]
